############################
# HTTP -> HTTPS REDIRECT
############################
server {
    listen 80;
    server_name csabolanta.hu api.csabolanta.hu;
    return 301 https://$host$request_uri;
}

############################
# FRONTEND - HTTPS
############################
server {
    listen 443 ssl;
    server_name csabolanta.hu;

    # Cloudflare Origin Certificate
    ssl_certificate     /etc/nginx/certs/xtracker.pem;
    ssl_certificate_key /etc/nginx/certs/xtracker.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    # Frontend (Vue SPA)
    root /usr/share/nginx/html;
    index index.html;


    # WEBSOCKET
    location ^~ /socket.io/ {
        proxy_pass http://websocket:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off;
        proxy_read_timeout 86400;
    }


    location / {
        try_files $uri $uri/ /index.html;
    }

    # ======================
    # BASIC AUTH (TEMP)
    # ======================
    auth_basic           "xtracker - restricted";
    auth_basic_user_file /etc/nginx/conf.d/.htpasswd;

}

############################
# API - HTTPS + FASTCGI
############################
server {
    listen 443 ssl;
    server_name api.csabolanta.hu;

    # Cloudflare Origin Certificate
    ssl_certificate     /etc/nginx/certs/xtracker.pem;
    ssl_certificate_key /etc/nginx/certs/xtracker.key;

    # SSL hardening
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    # Laravel public directory
    root /var/www/public;
    index index.php;

    location / {
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME /var/www/public/index.php;
        fastcgi_param DOCUMENT_ROOT   /var/www/public;
        fastcgi_param SCRIPT_NAME     /index.php;
        fastcgi_param PATH_INFO       $fastcgi_path_info;

        fastcgi_pass backend:9000;
    }
}
