name: Build and Release EXE

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests pyinstaller python-dotenv pypresence customtkinter darkdetect Pillow SimConnect

      - name: Create .env file
        shell: bash
        run: |
          echo "DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}" > XPlaneTracker/.env
          echo "DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }}" >> XPlaneTracker/.env

      - name: Build EXE
        working-directory: ./XPlaneTracker
        run: >
          pyinstaller --onedir --windowed --name "CSABOLANTA" --add-data ".env;." --collect-all customtkinter --collect-all SimConnect --hidden-import "darkdetect" --hidden-import "PIL" --hidden-import "PIL._tkinter_finder" --hidden-import "pypresence" --hidden-import "winreg" main.py


      - name: Zip release folder
        shell: pwsh
        run: Compress-Archive -Path XPlaneTracker/dist/CSABOLANTA -DestinationPath XPlaneTracker/dist/CSABOLANTA.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: XPlaneTracker/dist/CSABOLANTA.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
