name: Build and Release EXE

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests pyinstaller rich SimConnect python-dotenv pypresence customtkinter darkdetect Pillow

      - name: Create .env file
        shell: bash
        run: |
          echo "DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}" > XPlaneTracker/.env
          echo "DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }}" >> XPlaneTracker/.env

      - name: Build EXE
        working-directory: ./XPlaneTracker
        run: >
          pyinstaller --onefile --windowed --name "CSABOLANTA" --add-data ".env;." --collect-all customtkinter --collect-all SimConnect --hidden-import "darkdetect" --hidden-import "PIL" --hidden-import "PIL._tkinter_finder" main.py


      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: XPlaneTracker/dist/CSABOLANTA.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
